### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by theaspect** [xWillQ/BD#1]
1. В корне должны быть три скрипта: build.sh для сборки, run.sh для запуска и test.sh для тестирования
2. Класс должны быть в пакетах вида com.компания.проект
3. Каждый класс должен быть в отдельном одноименном файле, при этом модели должны находится в пакете com.компания.проект.domain
4. Аналогично предыдущему сервисы должны находиться в пакете com.компания.проект.service
5. Коды выхода должны быть вынесены в enum
6. Строки не должны быть длиннее 100 символов. Обрати внимание на вертикальную линию в файле.
7. Именование сервисов не соответствует code conventions. У тебя сервисы даже не классы просто набор функций в файле
8. Несколько раз на паре повторил что нельзя из одного файла обращаться к данным другого https://github.com/xWillQ/BD/blob/master/src/authentication.kt#L8
9. Права доступа вынести в enum
10. После этого для проверки наличия роли использовать метод values() созданного enum

**Comment by xwillq** [comment]
Исправлено в релизе 1.2
