### ISSUE TITLE
Review 3.0

### ISSUE THREAD

**Issue by theaspect** [xWillQ/BD#2]
1. коннект долежн создаваться в начале работы приложения и закрываться перед выходом из него.
2. Помним про букву I – коннект прокидывается внутрь сервисов
3. prepared statement и result set тоже должны закрываться после получения данных
4. миграции должны выполняться при помощи flyway
5. в логах ОБЯЗАТЕЛЬНО напишите: открываем коннект, закрываем коннект. Аналогично для prepared statement и result set я хочу видеть это на тревисе
6. все тестовые данные которые у нас были ранее должны добавиться в базу при помощи миграции и быть удалены из кода

**Comment by xwillq** [comment]
Исправил в релизе 3.1
